fix: Birthdate not saving for ro-RO due to format validation
vtex/profile-form pull request #85
Opened 2020-10-07 07:53 UTC by exilonX

#### What is the purpose of this pull request?
Fixing the save of birth date on profile edit for culture-info ro_RO

#### What problem is this solving?
Could not save the birth date because of wrong format, was DD/MM/YYYY and expected DD.MM.YYYY

#### How should this be manually tested?
Change the culture_info to ro_RO and try to save the profile. 

#### Screenshots or example usage

#### Types of changes
- [ ] Bug fix (a non-breaking change which fixes an issue)

2020-10-07 17:51 UTC, salesfelipe commented
Hey @exilonX , can you provide a working workspace with this change?

2020-10-07 17:52 UTC, salesfelipe requested changes

2020-10-07 17:52 UTC, salesfelipe commented on react/utils/dateRules.js
> +      ruleCopy.mask = rule.mask ? rule.mask : (value => msk.fit(value, '99/99/9999'));
Remove ;
```suggestion
      ruleCopy.mask = rule.mask ? rule.mask : (value => msk.fit(value, '99/99/9999'))
```

2020-10-07 17:52 UTC, salesfelipe commented on react/rules/ROU.js
>  import { isPastDate } from '../utils/dateRules'
Missing CHANGELOG entry

2020-10-08 06:44 UTC, exilonX commented
> Hey @exilonX , can you provide a working workspace with this change?

https://ionelwk--vtexromania.myvtex.com/

2020-10-08 12:53 UTC, salesfelipe requested changes

2020-10-08 12:53 UTC, salesfelipe commented on CHANGELOG.md
> +
```suggestion
```

This will be added later on

2020-10-09 07:30 UTC, exilonX commented on CHANGELOG.md
> +
Ok

2020-10-13 17:23 UTC, salesfelipe approved these changes

2020-10-14 12:51 UTC, merged