Fix/edit/birthdate ro
vtex/profile-form pull request #87
Opened 2020-10-08 08:24 UTC by exilonX

#### What is the purpose of this pull request?
Fixing the save of birth date on profile edit for culture-info ro_RO

#### What problem is this solving?
Could not save the birth date because of wrong format, was DD/MM/YYYY and expected DD.MM.YYYY

#### How should this be manually tested?
Change the culture_info to ro_RO and try to save the profile.
The changes should be active here [ionelwk]( https://ionelwk--vtexromania.myvtex.com/)

#### Types of changes
- [ ] Bug fix (a non-breaking change which fixes an issue)

2020-10-08 12:43 UTC, salesfelipe requested changes

2020-10-08 12:43 UTC, salesfelipe commented on CHANGELOG.md
> +
```suggestion
```

2020-10-08 12:43 UTC, salesfelipe commented on CHANGELOG.md
> +## [2.7.3] - 2020-10-08
This will be automatically updated

2020-10-08 12:50 UTC, salesfelipe commented
I saw that this works, but one question that came to my mind was, will this date be accepted by the other systems, like checkout? Did you try to close a purchase with this profile?

2020-10-09 07:55 UTC, exilonX commented
I placed an order on the vtexromania account and it worked.

2020-10-13 17:22 UTC, salesfelipe approved these changes

2020-10-14 13:12 UTC, merged